const GRAVITY = 350;
const BULLET_SPEED = 400;
const BULLET_LIFETIME = 2000;
const PLAYER_SHOOT_INTERVAL = 300;
const PLAYER_JUMP_POWER = -350;

export {
    GRAVITY,
    BULLET_SPEED,
    BULLET_LIFETIME,
    PLAYER_SHOOT_INTERVAL,
    PLAYER_JUMP_POWER
}
